language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer update $COMPOSER_FLAGS --prefer-dist

script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer fix --verbose --diff --dry-run
